services:
  portainer_agent:
    image: portainer/agent:2.19.5
    container_name: portainer_agent
    ports:
      - 9001:9001
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock \
      - /var/lib/docker/volumes:/var/lib/docker/volumes \

  nodeexporter:
    image: quay.io/prometheus/node-exporter:v1.8.1
    container_name: node_exporter
    command: "--path.rootfs=/host"
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave

    